[[annotation]]
file="hg19/annotations/processed_annotations/gnomad.genomes.r2.1.1.sites.AF.vcf.gz"
fields = ["AF"]
ops=["self"]
names=["gnomad_genome_AF"]

[[annotation]]
file="hg19/annotations/processed_annotations/gnomad.exomes.r2.1.1.sites.AF.vcf.gz"
fields = ["AF"]
ops=["self"]
names=["gnomad_exome_AF"]
